Changed scripts

diff --git a/.local/bin/tools/transadd b/.local/bin/tools/transadd
--- a/.local/bin/tools/transadd
+++ b/.local/bin/tools/transadd
@@ -1,9 +1,9 @@
-#!/usr/bin/env sh
+#!/bin/sh
 
 # Mimeapp script for adding torrent to transmission-daemon, but will also start the daemon first if not running.
 
-# transmission-daemon sometimes fails to take remote requests in its first moments.
+# transmission-daemon sometimes fails to take remote requests in its first moments, hence the sleep.
 
-pgrep -x transmission-da || (transmission-daemon && notify-send "Starting transmission daemon..." && sleep 3 && pkill -RTMIN+7 i3blocks)
+pidof transmission-daemon >/dev/null || (transmission-daemon && notify-send "Starting transmission daemon..." && sleep 3 && pkill -RTMIN+7 "${STATUSBAR:-dwmblocks}")
 
 transmission-remote -a "$@" && notify-send "🔽 Torrent added."
